### ISSUE TITLE
All bots crashed suddenly, playing music or not

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#10]
6 streamers running, 1 streamer wasn't playing any music at all. All of them crashed regardless. Logs respectively:
**General Stream**
```
DiscordStreamer: Streaming Martin Garrix & Jay Hardway - Spotless
/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:344
            throw new Error("Not ready yet");
            ^

Error: Not ready yet
    at VoiceConnection.play (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:344:19)
    at VoiceConnection.vc.on (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/discordstreamer/lib/VoiceManager.js:71:19)
    at emitNone (events.js:86:13)
    at VoiceConnection.emit (events.js:185:7)
    at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:459:14)
    at VoiceConnection._send (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:383:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
**Remix Stream**
```
DiscordStreamer: Streaming IZECOLD - Close (feat. Molly Ann) [Brooks Remix] | NCS x FHM Release
/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:344
            throw new Error("Not ready yet");
            ^

Error: Not ready yet
    at VoiceConnection.play (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:344:19)
    at VoiceConnection.vc.on (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/VoiceManager.js:71:19)
    at emitNone (events.js:86:13)
    at VoiceConnection.emit (events.js:185:7)
    at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:459:14)
    at VoiceConnection._send (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:383:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
**VEVO Stream**
```
DiscordStreamer: Streaming Shawn Mendes - Treat You Better
/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/voice/VoiceConnection.js:344
            throw new Error("Not ready yet");
            ^

Error: Not ready yet
    at VoiceConnection.play (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/voice/VoiceConnection.js:344:19)
    at VoiceConnection.vc.on (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/VoiceManager.js:71:19)
    at emitNone (events.js:86:13)
    at VoiceConnection.emit (events.js:185:7)
    at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/voice/VoiceConnection.js:459:14)
    at VoiceConnection._send (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/voice/VoiceConnection.js:383:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
**OmgStreamer**
```
DiscordStreamer: Streaming Marshmello - Alone (Official Music Video)
/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS OMG/node_modules/eris/lib/voice/VoiceConnection.js:344
            throw new Error("Not ready yet");
            ^

Error: Not ready yet
    at VoiceConnection.play (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS OMG/node_modules/eris/lib/voice/VoiceConnection.js:344:19)
    at VoiceConnection.vc.on (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS OMG/node_modules/discordstreamer/lib/VoiceManager.js:71:19)
    at emitNone (events.js:86:13)
    at VoiceConnection.emit (events.js:185:7)
    at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS OMG/node_modules/eris/lib/voice/VoiceConnection.js:459:14)
    at VoiceConnection._send (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS OMG/node_modules/eris/lib/voice/VoiceConnection.js:383:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
**Dev Stream**
```
DiscordStreamer: Streaming Tobu - Hope [NCS Release]
/home/mingxuanlim/Desktop/DS/node_modules/eris/lib/voice/VoiceConnection.js:344
            throw new Error("Not ready yet");
            ^

Error: Not ready yet
    at VoiceConnection.play (/home/mingxuanlim/Desktop/DS/node_modules/eris/lib/voice/VoiceConnection.js:344:19)
    at VoiceConnection.vc.on (/home/mingxuanlim/Desktop/DS/node_modules/discordstreamer/lib/VoiceManager.js:71:19)
    at emitNone (events.js:86:13)
    at VoiceConnection.emit (events.js:185:7)
    at VoiceConnection.stopPlaying (/home/mingxuanlim/Desktop/DS/node_modules/eris/lib/voice/VoiceConnection.js:459:14)
    at VoiceConnection._send (/home/mingxuanlim/Desktop/DS/node_modules/eris/lib/voice/VoiceConnection.js:383:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
**Pub-Dev Stream** (No music)
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at VoiceConnection.emit (events.js:163:17)
    at VoiceConnection.disconnect (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/voice/VoiceConnection.js:310:18)
    at VoiceConnection.connect (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/voice/VoiceConnection.js:121:18)
    at VoiceConnectionManager.voiceServerUpdate (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/voice/VoiceConnectionManager.js:53:36)
    at Shard.wsEvent (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/gateway/Shard.js:1158:46)
    at WebSocket.ws.onmessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/gateway/Shard.js:1417:34)
    at WebSocket.onMessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/WebSocket.js:841:10)
    at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:371:5)
    at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:499:31)
```

**Comment by cernodile** [comment]
It seems like you either lost your connection or Discord dropped all your bots.
