### ISSUE TITLE
Streamers are timing out again

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#32]
The streamers are timing out again, this time two bots timed out, one didn't crash but left the voice server, the other one crashed:
**Remix** (Crashed)
```
1|remix    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|remix    | Error: Voice connection timeout
1|remix    |     at Timeout.pendingGuilds.(anonymous function).timeout.setTimeout [as _onTimeout] (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnectionManager.js:31:25)
1|remix    |     at ontimeout (timers.js:365:14)
1|remix    |     at tryOnTimeout (timers.js:237:5)
1|remix    |     at Timer.listOnTimeout (timers.js:207:5)
1|remix    | TypeError: Cannot read property 'timeout' of undefined
1|remix    |     at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:443:24)
1|remix    |     at Object.fn (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/CommandManager.js:111:39)
1|remix    |     at Client.CommandClient.bot.on.msg (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/CommandManager.js:302:31)
1|remix    |     at emitOne (events.js:96:13)
1|remix    |     at Client.emit (events.js:188:7)
1|remix    |     at Shard.wsEvent (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/gateway/Shard.js:385:33)
1|remix    |     at WebSocket.ws.onmessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/gateway/Shard.js:1417:34)
1|remix    |     at WebSocket.onMessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/WebSocket.js:442:14)
1|remix    |     at emitTwo (events.js:106:13)
1|remix    |     at WebSocket.emit (events.js:191:7)
1|remix    |     at Receiver.ontext (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/WebSocket.js:841:10)
1|remix    |     at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:536:18
1|remix    |     at Receiver.applyExtensions (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:371:5)
1|remix    |     at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:508:14
1|remix    |     at Receiver.flush (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:347:3)
1|remix    |     at Receiver.finish (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:541:12)
1|remix    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|remix    | Error: Unknown error encountered!
1|remix    | Connection is closed.
1|remix    |     at Worker.__dbError (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/Worker.js:155:13)
1|remix    |     at r.table.run.then.catch.e (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/Worker.js:174:14)
1|remix    |     at tryCatcher (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/util.js:26:23)
1|remix    |     at Promise._settlePromiseFromHandler (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/promise.js:510:31)
1|remix    |     at Promise._settlePromiseAt (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/promise.js:584:18)
1|remix    |     at Promise._settlePromises (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/promise.js:700:14)
1|remix    |     at Async._drainQueue (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/async.js:123:16)
1|remix    |     at Async._drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/async.js:133:10)
1|remix    |     at Immediate.Async.drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/async.js:15:14)
1|remix    |     at runCallback (timers.js:649:20)
1|remix    |     at tryOnImmediate (timers.js:622:5)
1|remix    |     at processImmediate [as _immediateCallback] (timers.js:594:5)
1|remix    | Unhandled rejection Error: Unknown error encountered!
1|remix    | Connection is closed.
1|remix    |     at Worker.__dbError (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/Worker.js:155:13)
1|remix    |     at r.table.run.then.catch.e (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/Worker.js:174:14)
1|remix    |     at tryCatcher (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/util.js:26:23)
1|remix    |     at Promise._settlePromiseFromHandler (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/promise.js:510:31)
1|remix    |     at Promise._settlePromiseAt (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/promise.js:584:18)
1|remix    |     at Promise._settlePromises (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/promise.js:700:14)
1|remix    |     at Async._drainQueue (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/async.js:123:16)
1|remix    |     at Async._drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/async.js:133:10)
1|remix    |     at Immediate.Async.drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/bluebird/js/main/async.js:15:14)
1|remix    |     at runCallback (timers.js:649:20)
1|remix    |     at tryOnImmediate (timers.js:622:5)
1|remix    |     at processImmediate [as _immediateCallback] (timers.js:594:5)
1|remix    | TypeError: Cannot read property 'message' of undefined
1|remix    |     at VoiceConnection.vc.on (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/discordstreamer/lib/VoiceManager.js:57:14)
1|remix    |     at emitOne (events.js:96:13)
1|remix    |     at VoiceConnection.emit (events.js:188:7)
1|remix    |     at VoiceConnection.disconnect (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:320:18)
1|remix    |     at VoiceConnection.connect (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnection.js:121:18)
1|remix    |     at VoiceConnectionManager.voiceServerUpdate (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/voice/VoiceConnectionManager.js:53:36)
1|remix    |     at Shard.wsEvent (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/gateway/Shard.js:1158:46)
1|remix    |     at WebSocket.ws.onmessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/eris/lib/gateway/Shard.js:1417:34)
1|remix    |     at WebSocket.onMessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/WebSocket.js:442:14)
1|remix    |     at emitTwo (events.js:106:13)
1|remix    |     at WebSocket.emit (events.js:191:7)
1|remix    |     at Receiver.ontext (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/WebSocket.js:841:10)
1|remix    |     at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:536:18
1|remix    |     at Receiver.applyExtensions (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:371:5)
1|remix    |     at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:508:14
1|remix    |     at Receiver.flush (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/Receiver.js:347:3)
1|remix    | Error: unexpected server response (520)
1|remix    |     at ClientRequest.response (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/WebSocket.js:719:15)
1|remix    |     at ClientRequest.g (events.js:292:16)
1|remix    |     at emitOne (events.js:96:13)
1|remix    |     at ClientRequest.emit (events.js:188:7)
1|remix    |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
1|remix    |     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
1|remix    |     at TLSSocket.socketOnData (_http_client.js:362:20)
1|remix    |     at emitOne (events.js:96:13)
1|remix    |     at TLSSocket.emit (events.js:188:7)
1|remix    |     at readableAddChunk (_stream_readable.js:176:18)
1|remix    |     at TLSSocket.Readable.push (_stream_readable.js:134:10)
1|remix    |     at TLSWrap.onread (net.js:551:20)
1|remix    | Error: unexpected server response (520)
1|remix    |     at ClientRequest.response (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS NT/node_modules/ws/lib/WebSocket.js:719:15)
1|remix    |     at ClientRequest.g (events.js:292:16)
1|remix    |     at emitOne (events.js:96:13)
1|remix    |     at ClientRequest.emit (events.js:188:7)
1|remix    |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
1|remix    |     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
1|remix    |     at TLSSocket.socketOnData (_http_client.js:362:20)
1|remix    |     at emitOne (events.js:96:13)
1|remix    |     at TLSSocket.emit (events.js:188:7)
1|remix    |     at readableAddChunk (_stream_readable.js:176:18)
1|remix    |     at TLSSocket.Readable.push (_stream_readable.js:134:10)
1|remix    |     at TLSWrap.onread (net.js:551:20)
```
**VEVO** (Left voice server)
```
2|vevo     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2|vevo     | Error: Voice connection timeout
2|vevo     |     at Timeout.pendingGuilds.(anonymous function).timeout.setTimeout [as _onTimeout] (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/voice/VoiceConnectionManager.js:31:25)
2|vevo     |     at ontimeout (timers.js:365:14)
2|vevo     |     at tryOnTimeout (timers.js:237:5)
2|vevo     |     at Timer.listOnTimeout (timers.js:207:5)
2|vevo     | TypeError: Cannot read property 'timeout' of undefined
2|vevo     |     at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/voice/VoiceConnection.js:443:24)
2|vevo     |     at Object.fn (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/CommandManager.js:111:39)
2|vevo     |     at Client.CommandClient.bot.on.msg (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/CommandManager.js:302:31)
2|vevo     |     at emitOne (events.js:96:13)
2|vevo     |     at Client.emit (events.js:188:7)
2|vevo     |     at Shard.wsEvent (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/gateway/Shard.js:385:33)
2|vevo     |     at WebSocket.ws.onmessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/eris/lib/gateway/Shard.js:1417:34)
2|vevo     |     at WebSocket.onMessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/WebSocket.js:442:14)
2|vevo     |     at emitTwo (events.js:106:13)
2|vevo     |     at WebSocket.emit (events.js:191:7)
2|vevo     |     at Receiver.ontext (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/WebSocket.js:841:10)
2|vevo     |     at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/Receiver.js:536:18
2|vevo     |     at Receiver.applyExtensions (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/Receiver.js:371:5)
2|vevo     |     at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/Receiver.js:508:14
2|vevo     |     at Receiver.flush (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/Receiver.js:347:3)
2|vevo     |     at Receiver.finish (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/ws/lib/Receiver.js:541:12)
2|vevo     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2|vevo     | Error: Unknown error encountered!
2|vevo     | Connection is closed.
2|vevo     |     at Worker.__dbError (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/Worker.js:155:13)
2|vevo     |     at r.table.run.then.catch.e (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/Worker.js:174:14)
2|vevo     |     at tryCatcher (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/util.js:26:23)
2|vevo     |     at Promise._settlePromiseFromHandler (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:510:31)
2|vevo     |     at Promise._settlePromiseAt (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:584:18)
2|vevo     |     at Promise._settlePromises (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:700:14)
2|vevo     |     at Async._drainQueue (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:123:16)
2|vevo     |     at Async._drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:133:10)
2|vevo     |     at Immediate.Async.drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:15:14)
2|vevo     |     at runCallback (timers.js:649:20)
2|vevo     |     at tryOnImmediate (timers.js:622:5)
2|vevo     |     at processImmediate [as _immediateCallback] (timers.js:594:5)
2|vevo     | Unhandled rejection Error: Unknown error encountered!
2|vevo     | Connection is closed.
2|vevo     |     at Worker.__dbError (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/Worker.js:155:13)
2|vevo     |     at r.table.run.then.catch.e (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/Worker.js:174:14)
2|vevo     |     at tryCatcher (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/util.js:26:23)
2|vevo     |     at Promise._settlePromiseFromHandler (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:510:31)
2|vevo     |     at Promise._settlePromiseAt (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:584:18)
2|vevo     |     at Promise._settlePromises (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:700:14)
2|vevo     |     at Async._drainQueue (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:123:16)
2|vevo     |     at Async._drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:133:10)
2|vevo     |     at Immediate.Async.drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:15:14)
2|vevo     |     at runCallback (timers.js:649:20)
2|vevo     |     at tryOnImmediate (timers.js:622:5)
2|vevo     |     at processImmediate [as _immediateCallback] (timers.js:594:5)
2|vevo     | Unhandled rejection Error: Unknown error encountered!
2|vevo     | Connection is closed.
2|vevo     |     at Worker.__dbError (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/Worker.js:155:13)
2|vevo     |     at r.table.run.then.catch.e (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/discordstreamer/lib/Worker.js:174:14)
2|vevo     |     at tryCatcher (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/util.js:26:23)
2|vevo     |     at Promise._settlePromiseFromHandler (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:510:31)
2|vevo     |     at Promise._settlePromiseAt (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:584:18)
2|vevo     |     at Promise._settlePromises (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/promise.js:700:14)
2|vevo     |     at Async._drainQueue (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:123:16)
2|vevo     |     at Async._drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:133:10)
2|vevo     |     at Immediate.Async.drainQueues (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS VEVO/node_modules/bluebird/js/main/async.js:15:14)
2|vevo     |     at runCallback (timers.js:649:20)
2|vevo     |     at tryOnImmediate (timers.js:622:5)
2|vevo     |     at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by itslukej** [comment]
![image](https://cloud.githubusercontent.com/assets/8759737/21582617/990e3ac2-d057-11e6-8f83-4585e4980470.png)

**Comment by jaacks** [comment]
That's it^

**Comment by DoctorDarkMagic** [comment]
Thanks luke.
