### ISSUE TITLE
Missing ffmpeg shouldn't crash the bot

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#33]
When the dependency ffmpeg is missing, Windows returns:
```
8|main     | Error: Neither ffmpeg nor avconv was found. Make sure you installed
 either one, and check that it is in your PATH
8|main     |     at VoiceConnection.pickCommand (D:\Discord\DS\node_modules\eris
\lib\voice\VoiceConnection.js:576:15)
8|main     |     at VoiceConnection (D:\Discord\DS\node_modules\eris\lib\voice\V
oiceConnection.js:103:29)
8|main     |     at VoiceConnectionManager.voiceServerUpdate (D:\Discord\DS\node
_modules\eris\lib\voice\VoiceConnectionManager.js:46:42)
8|main     |     at Shard.wsEvent (D:\Discord\DS\node_modules\eris\lib\gateway\S
hard.js:1158:46)
8|main     |     at WebSocket.ws.onmessage.err (D:\Discord\DS\node_modules\eris\
lib\gateway\Shard.js:1417:34)
8|main     |     at WebSocket.onMessage (D:\Discord\DS\node_modules\ws\lib\WebSo
cket.js:442:14)
8|main     |     at emitTwo (events.js:106:13)
8|main     |     at WebSocket.emit (events.js:191:7)
8|main     |     at Receiver.ontext (D:\Discord\DS\node_modules\ws\lib\WebSocket
.js:841:10)
8|main     |     at D:\Discord\DS\node_modules\ws\lib\Receiver.js:536:18
8|main     |     at Receiver.applyExtensions (D:\Discord\DS\node_modules\ws\lib\
Receiver.js:371:5)
8|main     |     at D:\Discord\DS\node_modules\ws\lib\Receiver.js:508:14
8|main     |     at Receiver.flush (D:\Discord\DS\node_modules\ws\lib\Receiver.j
s:347:3)
8|main     |     at Receiver.finish (D:\Discord\DS\node_modules\ws\lib\Receiver.
js:541:12)
8|main     |     at Receiver.expectHandler (D:\Discord\DS\node_modules\ws\lib\Re
ceiver.js:499:31)
8|main     |     at Receiver.add (D:\Discord\DS\node_modules\ws\lib\Receiver.js:
103:24)
```
(and on pm2 it spams the chat and logs) It shouldn't crash the bot, it should instead return an error: `ERR: missing dependency 'ffmpeg'! aborting initialization` or something along that line...

**Comment by jaacks** [comment]
Considering that FFMPEG is the main way of streaming music through the library, it would be required.

**Comment by GameplaysRFun** [comment]
Yes, but instead of spamming crash logs, maybe it should end the process with a message - if it's possible.

**Comment by cernodile** [comment]
@GameplaysRFun That's PM2 side-effect, it should crash if it's not on PM2.
