### ISSUE TITLE
Bot crashed suddenly

### ISSUE THREAD

**Issue by LimMingXuan** [TeamCernodile/DiscordStreamer#7]
```
DiscordStreamer: Streaming Chime & Adam Tell - Whole [NCS Release]
/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:0



TypeError: unexpected type [object Null], use Uint8Array
    at checkArrayTypes (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/tweetnacl/nacl-fast.js:2152:14)
    at Object.nacl.secretbox (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/tweetnacl/nacl-fast.js:2175:3)
    at VoiceConnection._createPacket (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:468:23)
    at VoiceConnection._send (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS/node_modules/eris/lib/voice/VoiceConnection.js:420:31)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Crashed all of a sudden when streaming.

**Comment by cernodile** [comment]
I believe it might come from unfinished downloaded file.
Try streaming same song again, and if reoccurs then please remove the .mp3 file of the song that caused this, and try to stream same song again.
