### ISSUE TITLE
->reshuffle shouldn't crash the bot

### ISSUE THREAD

**Issue by GameplaysRFun** [TeamCernodile/DiscordStreamer#9]
->reshuffle crashes the bot when the playlist is empty. Instead, it should send a message to the user saying "No songs available!" or something like that, and leaving the bot in an online state.

```
DiscordStreamer: Gameplays R Fun#5015 executed <remove EP625xQIGzs>
DiscordStreamer: Gameplays R Fun#5015 executed <reshuffle>
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined
    at VoiceConnection.vc.on (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/discordstreamer/lib/VoiceManager.js:56:71)
    at emitNone (events.js:86:13)
    at VoiceConnection.emit (events.js:185:7)
    at VoiceConnection.stopPlaying (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/voice/VoiceConnection.js:459:14)
    at Object.fn (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/discordstreamer/lib/CommandManager.js:114:37)
    at Client.CommandClient.bot.on.msg (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/discordstreamer/lib/CommandManager.js:255:29)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Shard.wsEvent (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/gateway/Shard.js:385:33)
    at WebSocket.ws.onmessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/eris/lib/gateway/Shard.js:1417:34)
    at WebSocket.onMessage (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/WebSocket.js:841:10)
    at /media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/media/mingxuanlim/5A507F6B507F4CAF/Discord/DS PDEV/node_modules/ws/lib/Receiver.js:371:5)
```

**Comment by cernodile** [comment]
Interesting, will see what I can do about it, thanks.

**Comment by cernodile** [comment]
Should be fixed in upcoming release.
